[main]
font=FiraCode Nerd Font:size=14
terminal=kitty
prompt="❯ "
layer=overlay

# Sizing
width=40
lines=10
horizontal-pad=20
vertical-pad=15
inner-pad=5

[colors]
# Background: Dark Slate (with 98% opacity for slight blur effect)
background=1A2024f0
# Text: Icy White
text=D3E0E2ff
# Prompt/Match: Aquamarine
match=7FFFD4ff
# Selection Background: Lighter Slate
selection=34424Aff
# Selection Text: Icy White
selection-text=D3E0E2ff
# Selection Match (What you type): Bloodstone Red
selection-match=C61A1Aff
# Border: Aquamarine
border=7FFFD4ff

[border]
width=2
radius=8
