##############################
###      Sources           ###
##############################

source = ./autostart.conf
source = ./binds.conf
source = ./env.conf
source = ./inputs.conf
source = ./layout.conf
source = ./layrules.conf
source = ./monitors.conf
source = ./permissions.conf
source = ./winrules.conf

source = /home/tbear/.config/hypr/noctalia/noctalia-colors.conf

